#!/bin/bash

# Script para mostrar la estructura del proyecto

echo "🏥 Estructura del Proyecto - Sistema de Citas Médicas"
echo ""
echo "Proyecto Citas Medicas/"
echo "│"
echo "├── 📄 Dockerfile              (Configuración PHP-Apache)"
echo "├── 📄 docker-compose.yml      (Orquestación de servicios)"
echo "├── 📄 .env                    (Variables de entorno)"
echo "├── 📄 .gitignore              (Archivos ignorados por git)"
echo "│"
echo "├── 📂 config/                 (Configuración)"
echo "│   ├── init.sql               (Script de inicialización BD)"
echo "│   └── apache.conf            (Configuración Apache)"
echo "│"
echo "├── 📂 src/                    (Código fuente)"
echo "│   ├── 📄 index.php           (Página de inicio)"
echo "│   ├── 📄 agendar-cita.php    (Formulario de agendamiento)"
echo "│   ├── 📄 procesar-cita.php   (Procesamiento de citas)"
echo "│   ├── 📄 mis-citas.php       (Listado de citas)"
echo "│   ├── 📄 medicos.php         (Listado de médicos)"
echo "│   ├── 📄 config.php          (Configuración y conexión BD)"
echo "│   ├── 📄 helpers.php         (Funciones auxiliares)"
echo "│   │"
echo "│   ├── 📂 models/             (Clases de datos)"
echo "│   │   ├── Cita.php           (Gestión de citas)"
echo "│   │   └── Medico.php         (Gestión de médicos)"
echo "│   │"
echo "│   ├── 📂 controllers/        (Lógica de negocio)"
echo "│   ├── 📂 views/              (Vistas reutilizables)"
echo "│   │"
echo "│   └── 📂 assets/             (Recursos estáticos)"
echo "│       ├── css/"
echo "│       │   └── style.css      (Estilos principales)"
echo "│       └── js/                (Scripts JavaScript)"
echo "│"
echo "├── 📄 start.bat               (Script de inicio - Windows)"
echo "├── 📄 start.sh                (Script de inicio - Linux/Mac)"
echo "│"
echo "├── 📄 README.md               (Documentación completa)"
echo "├── 📄 QUICK_START.md          (Guía rápida de inicio)"
echo "└── 📄 TECHNICAL.md            (Documentación técnica)"
echo ""
echo "═══════════════════════════════════════════════════════"
echo ""
echo "🐳 SERVICIOS DOCKER"
echo ""
echo "  ✓ PHP-Apache (Puerto 80)"
echo "  ✓ MySQL 8.0 (Puerto 3306)"
echo "  ✓ phpMyAdmin (Puerto 8080)"
echo ""
echo "═══════════════════════════════════════════════════════"
echo ""
echo "🚀 PARA INICIAR:"
echo ""
echo "  Windows: .\start.bat"
echo "  Linux/Mac: bash start.sh"
echo "  Manual: docker-compose up -d"
echo ""
echo "═══════════════════════════════════════════════════════"
